odu_administrative.settings:
  type: config_object
  label: 'ODU administrative module settings'
  mapping:
    use_formassembly_static_caching:
      type: boolean
      label: 'Enable static caching proxy for Form Assembly embeds'
    odu_nofollow_whitelist:
      type: string
      label: 'Domains to whitelist from having nofollow applied to links'