_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor5: 0
  components: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  current_page_entity_tokens: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  eck: 0
  editor: 0
  embed: 0
  embederator: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  frontback: 0
  geocoder: 0
  geocoder_field: 0
  geofield: 0
  geofield_zip_proximity: 0
  gin_login: 0
  gin_moderation_sidebar: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  leaflet: 0
  leaflet_views: 0
  link: 0
  linkit: 0
  masquerade: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_async_widget: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  moderation_sidebar: 0
  mysql: 0
  name: 0
  node: 0
  odu_administrative: 0
  odu_course_launchers: 0
  odu_custom: 0
  odu_emsi: 0
  odu_mailboxvalidator: 0
  odu_migrate: 0
  options: 0
  other_view_filter: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  quick_node_clone: 0
  rabbit_hole: 0
  rebuild_cache_access: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  rh_node: 0
  shortcut: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  single_content_sync: 0
  svg_image: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  viewfield: 0
  viewfield_argument_helper: 0
  views_argument_token: 0
  views_bulk_operations: 0
  views_infinite_scroll: 0
  views_taxonomy_term_name_into_id: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  gin: 0
  d10starter: 0
profile: standard
